import os
import re
from typing import Callable, Iterable

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:  # pragma: no cover
    psycopg = None
    dict_row = None


class CompatRow(dict):
    __slots__ = ("_cols",)

    def __init__(self, data: dict):
        super().__init__(data)
        self._cols = list(data.keys())

    def __getitem__(self, key):
        if isinstance(key, int):
            return super().__getitem__(self._cols[key])
        return super().__getitem__(key)

    def get(self, key, default=None):
        if isinstance(key, int):
            try:
                key = self._cols[key]
            except Exception:
                return default
        return super().get(key, default)


def is_postgres_env() -> bool:
    engine = (os.environ.get("COG_DB_ENGINE") or "").strip().lower()
    if engine in {"postgres", "postgresql", "pg", "psycopg"}:
        return True
    url = (os.environ.get("COG_DATABASE_URL") or os.environ.get("DATABASE_URL") or "").strip().lower()
    return url.startswith("postgres://") or url.startswith("postgresql://")


def _convert_qmark_to_percent_s(sql: str) -> str:
    out = []
    in_single = False
    in_double = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                out.append("''")
                i += 2
                continue
            in_single = not in_single
            out.append(ch)
        elif ch == '"' and not in_single:
            in_double = not in_double
            out.append(ch)
        elif ch == "?" and not in_single and not in_double:
            out.append("%s")
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _replace_date_calls(sql: str) -> str:
    return re.sub(r"\bdate\(([^\)]+)\)", r"CAST(\1 AS DATE)", sql)


def _normalize_sql_for_postgres(sql: str) -> str | None:
    s = (sql or "").strip()
    if not s:
        return None
    if re.match(r"^PRAGMA\s+foreign_keys\s*=\s*ON\s*;?$", s, re.I):
        return None
    if re.match(r"^CREATE\s+TRIGGER\b", s, re.I | re.S):
        # SQLite trigger syntax is not compatible; app works without these
        # because folios are backfilled during init and can be generated later.
        return None

    s = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", s, flags=re.I)
    s = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", s, flags=re.I)
    s = re.sub(r"\bSELECT\s+last_insert_rowid\(\)\s+AS\s+id\b", "SELECT LASTVAL() AS id", s, flags=re.I)
    s = re.sub(r"strftime\('%Y%m%d'\s*,\s*'now'\)", "TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD')", s, flags=re.I)
    s = re.sub(r"strftime\('%Y'\s*,\s*([^\)]+)\)", r"TO_CHAR(CAST(\1 AS TIMESTAMP), 'YYYY')", s, flags=re.I)
    s = re.sub(r"strftime\('%m'\s*,\s*([^\)]+)\)", r"TO_CHAR(CAST(\1 AS TIMESTAMP), 'MM')", s, flags=re.I)
    s = re.sub(r"printf\('%06d'\s*,\s*([^\)]+)\)", r"LPAD(CAST(\1 AS TEXT), 6, '0')", s, flags=re.I)
    s = _convert_qmark_to_percent_s(s)
    s = _replace_date_calls(s)

    if re.search(r"\bINSERT\s+INTO\b", s, re.I) and "ON CONFLICT" not in s.upper():
        stripped = s.rstrip().rstrip(';')
        if sql.strip().upper().startswith("INSERT OR IGNORE"):
            s = stripped + " ON CONFLICT DO NOTHING"
    return s


def _split_sql_script(script: str) -> list[str]:
    statements: list[str] = []
    buf: list[str] = []
    in_single = False
    in_double = False
    in_line_comment = False
    in_block_comment = False
    i = 0
    while i < len(script):
        ch = script[i]
        nxt = script[i + 1] if i + 1 < len(script) else ""
        if in_line_comment:
            buf.append(ch)
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            buf.append(ch)
            if ch == "*" and nxt == "/":
                buf.append(nxt)
                i += 2
                in_block_comment = False
                continue
            i += 1
            continue
        if not in_single and not in_double:
            if ch == "-" and nxt == "-":
                buf.append(ch); buf.append(nxt)
                i += 2
                in_line_comment = True
                continue
            if ch == "/" and nxt == "*":
                buf.append(ch); buf.append(nxt)
                i += 2
                in_block_comment = True
                continue
        if ch == "'" and not in_double:
            if in_single and nxt == "'":
                buf.append(ch); buf.append(nxt)
                i += 2
                continue
            in_single = not in_single
            buf.append(ch)
            i += 1
            continue
        if ch == '"' and not in_single:
            in_double = not in_double
            buf.append(ch)
            i += 1
            continue
        if ch == ";" and not in_single and not in_double:
            stmt = "".join(buf).strip()
            if stmt:
                statements.append(stmt)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements


def _row_from_any(data) -> CompatRow | None:
    if data is None:
        return None
    if isinstance(data, CompatRow):
        return data
    if isinstance(data, dict):
        return CompatRow(data)
    return data


class PostgresCompatCursor:
    def __init__(self, conn, raw_cursor, rewrite_sql: Callable[[str], str] | None = None):
        self._conn = conn
        self._cur = raw_cursor
        self._rewrite_sql = rewrite_sql or (lambda s: s)
        self._manual_rows = None
        self.description = None

    def _set_manual_rows(self, rows: list[dict]):
        self._manual_rows = [CompatRow(r) for r in rows]
        if rows:
            self.description = [(k,) for k in rows[0].keys()]
        else:
            self.description = []

    def execute(self, sql, parameters=()):
        raw_sql = self._rewrite_sql(sql)
        txt = (raw_sql or "").strip()
        m = re.match(r"^PRAGMA\s+table_info\(([^\)]+)\)\s*$", txt, re.I)
        if m:
            table = m.group(1).strip().strip('"').strip("'")
            q = """
                SELECT ordinal_position - 1 AS cid,
                       column_name AS name,
                       data_type AS type,
                       CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
                       column_default AS dflt_value,
                       CASE WHEN EXISTS (
                           SELECT 1
                           FROM information_schema.table_constraints tc
                           JOIN information_schema.key_column_usage kcu
                             ON tc.constraint_name = kcu.constraint_name
                            AND tc.table_schema = kcu.table_schema
                          WHERE tc.table_schema = current_schema()
                            AND tc.table_name = %s
                            AND tc.constraint_type = 'PRIMARY KEY'
                            AND kcu.column_name = c.column_name
                       ) THEN 1 ELSE 0 END AS pk
                  FROM information_schema.columns c
                 WHERE table_schema = current_schema() AND table_name = %s
                 ORDER BY ordinal_position
            """
            self._cur.execute(q, (table, table))
            self._set_manual_rows(list(self._cur.fetchall()))
            return self
        if re.match(r"^SELECT\s+name\s+FROM\s+sqlite_master\s+WHERE\s+type='table'", txt, re.I):
            self._cur.execute(
                "SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type='BASE TABLE' ORDER BY table_name"
            )
            self._set_manual_rows(list(self._cur.fetchall()))
            return self
        normalized = _normalize_sql_for_postgres(raw_sql)
        self._manual_rows = None
        if not normalized:
            self.description = []
            return self
        self._cur.execute(normalized, parameters)
        self.description = self._cur.description
        return self

    def executemany(self, sql, seq_of_parameters: Iterable[tuple]):
        normalized = _normalize_sql_for_postgres(self._rewrite_sql(sql))
        self._manual_rows = None
        if normalized:
            self._cur.executemany(normalized, seq_of_parameters)
            self.description = self._cur.description
        return self

    def executescript(self, sql_script: str):
        self._manual_rows = None
        for stmt in _split_sql_script(sql_script):
            normalized = _normalize_sql_for_postgres(self._rewrite_sql(stmt))
            if normalized:
                self._cur.execute(normalized)
        self.description = self._cur.description
        return self

    def fetchone(self):
        if self._manual_rows is not None:
            if not self._manual_rows:
                return None
            return self._manual_rows.pop(0)
        return _row_from_any(self._cur.fetchone())

    def fetchall(self):
        if self._manual_rows is not None:
            rows = self._manual_rows
            self._manual_rows = []
            return rows
        return [_row_from_any(r) for r in self._cur.fetchall()]

    @property
    def rowcount(self):
        return self._cur.rowcount

    def close(self):
        return self._cur.close()


class PostgresCompatConnection:
    def __init__(self, raw_conn, rewrite_sql: Callable[[str], str] | None = None):
        self._conn = raw_conn
        self._rewrite_sql = rewrite_sql or (lambda s: s)

    def cursor(self, factory=None):
        cur = self._conn.cursor(row_factory=dict_row)
        return PostgresCompatCursor(self, cur, rewrite_sql=self._rewrite_sql)

    def execute(self, sql, parameters=()):
        cur = self.cursor()
        cur.execute(sql, parameters)
        return cur

    def executescript(self, sql_script: str):
        cur = self.cursor()
        cur.executescript(sql_script)
        return cur

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()


def build_postgres_connection(rewrite_sql: Callable[[str], str] | None = None):
    if psycopg is None:
        raise RuntimeError("psycopg is not installed. Add psycopg[binary] to requirements.")
    dsn = os.environ.get("COG_DATABASE_URL") or os.environ.get("DATABASE_URL")
    if not dsn:
        raise RuntimeError("Missing COG_DATABASE_URL or DATABASE_URL for PostgreSQL mode.")
    raw = psycopg.connect(dsn)
    raw.autocommit = False
    return PostgresCompatConnection(raw, rewrite_sql=rewrite_sql)
